language: ruby
cache: bundler

rvm:
 - 2.3.0
 
gemfile:
  - Gemfile

branches:
  only:
    - master

env:
  - RAILS_ENV=test DB=sqlite
  
addons:
  mariadb: '10.0'
  
services:
  - mysql

before_script:
  - "bundle exec rake prepare_test_env"

before_install:
  - mysql -e 'create database imp_test;'

script: "bundle exec rspec"